### ISSUE TITLE
I Have a Pretty Good Idea.

### ISSUE THREAD

**Issue by Khubayan** [BananaLeaf77/steam-price-alerter#1]
**JUST REWRITE IT USING NODEJS, LOL.**

**Comment by BananaLeaf77** [comment]
shut up and do drugs

**Comment by Khubayan** [comment]
Close the issue u dummy  airhead

**Comment by BananaLeaf77** [comment]
![Uploading blackman selfie.jpg…]()

**Comment by BananaLeaf77** [comment]
kys (keep yourself safe)


<img src= "https://64.media.tumblr.com/tumblr_mc02713Cbr1rdq2opo1_500.gif" />
